export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const SELECTED_PROJECT = "SELECTED_PROJECT";
export const DESELECT_PROJECT = "DESELECT_PROJECT";

export const GET_PROJECTS = "GET_PROJECTS";
export const UNLOAD_PROJECTS = "UNLOAD_PROJECTS";
export const ADD_PROJECT = "ADD_PROJECT";
export const DELETE_PROJECT = "DELETE_PROJECT";
export const EDIT_PROJECT = "EDIT_PROJECT";
export const PROJECTS_LOADING = "PROJECTS_LOADING";
export const PROJECT_EDITING = "PROJECT_EDITING";
export const PROJECT_EDITED = "PROJECT_EDITED";
export const PROJECT_ADDING = "PROJECT_ADDING";
export const PROJECT_ADDED = "PROJECT_ADDED";

export const SELECTED_DM = "SELECTED_DM";
export const DESELECT_DM = "DESELECT_DM";

export const GET_DMS = "GET_DMS";
export const UNLOAD_DMS = "UNLOAD_DMS";
export const ADD_DM = "ADD_DM";
export const DELETE_DM = "DELETE_DM";
export const DMS_LOADING = "DMS_LOADING";
